# Generated by Django 4.2.5 on 2023-09-30 01:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('annual_income', models.IntegerField()),
                ('credit_score', models.IntegerField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tenure', models.IntegerField()),
                ('emi_amount', models.IntegerField()),
                ('last_emi_amount', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('next_due_date', models.DateField()),
                ('paid_terms', models.IntegerField()),
                ('emi_due', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('CAR', 'CAR'), ('HOME', 'HOME'), ('EDUCATION', 'EDUCATION'), ('PERSONAL', 'PERSONAL')], max_length=20)),
                ('loan_amount', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('term_period', models.IntegerField()),
                ('disbursement_date', models.DateField()),
                ('total_repayable', models.IntegerField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('emi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.emi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount_paid', models.IntegerField()),
                ('emi_term', models.IntegerField()),
                ('principal', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loan')),
            ],
        ),
    ]
