# Generated by Django 4.2.5 on 2023-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
