# Generated by Django 4.2.5 on 2023-10-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.emi'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_repayable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
