# Generated by Django 4.2.5 on 2023-10-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_loan_emi_alter_loan_total_repayable'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='flat_interest',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
