# Generated by Django 4.2.5 on 2023-10-01 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emi_flat_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='emi_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='interest',
            field=models.FloatField(),
        ),
    ]
