# Generated by Django 4.2.5 on 2023-10-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaction_emi_date_alter_transaction_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='emi_date',
            field=models.DateField(),
        ),
    ]
