# Generated by Django 4.2.5 on 2023-10-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_transaction_emi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='aadhar',
            field=models.CharField(max_length=15),
        ),
    ]
