# Generated by Django 4.2.5 on 2023-10-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_appuser_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='aadhar',
            field=models.CharField(max_length=50),
        ),
    ]
